linters:
  enable-all: true

  disable:
    - deadcode
    - exhaustivestruct
    - gci
    - goerr113
    - gofumpt
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - wsl

issues:
  exclude-rules:
    # We need some way to interact with the user and stdout is a good
    # choice.
    - path: cmd/.+\.go$
      linters:
        - forbidigo

    # Tests are probably going to run long when you include all the
    # context directly in the test. It's also possible to run over if
    # doing a table test.
    - path: _test\.go$
      linters:
        - funlen

    - path: (_test|mocks)\.go$
      text: Use of weak random number generator
      linters:
        - gosec

    # Pretty much every field in cobra.Command is optional
    - text: cobra.Command is missing fields
      linters:
        - exhaustruct

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/durandj/git-ignore
          - github.com/go-git/go-git/v5
          - github.com/logrusorgru/aurora/v4
          - github.com/stretchr/testify/require
          - github.com/spf13/cobra

  revive:
    rules:
      - name: package-comments
        disabled: true
