# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

nfpms:
  - id: deb
    description: |
      A CLI tool for Git to generate `.gitignore` files for your repository.
    license: "MIT"
    homepage: "https://github.com/durandj/git-ignore"
    maintainer: "James Durand"
    section: "default"
    priority: "extra"
    contents:
      - src: ./git-ignore
        dst: /usr/bin/git-ignore
