language: go

go:
  - 1.11.x
  - master

before_script:
  - wget https://github.com/go-task/task/releases/download/v2.4.0/task_linux_amd64.deb
  - dpkg -i task_linux_amd64.deb
  - rm task_linux_amd64.deb
  - task install

script: skip

jobs:
  include:
    - stage: test
      env:
        - GO111MODULE=on
      install: go get -u
      script:
        - task test

    - stage: deploy
      install: go get -u
      script:
        - task deploy
      if: branch = master
