language: go

jobs:
  include:
    - stage: test
      name: Go 1.11.x Tests

      env:
        - GO111MODULE=on

      install: go get

      before_script:
        - wget https://github.com/go-task/task/releases/download/v2.4.0/task_linux_amd64.deb
        - sudo dpkg -i task_linux_amd64.deb
        - rm task_linux_amd64.deb
        - task install
      script:
        - task test

    - stage: test
      name: Go master Tests

      env:
        - GO111MODULE=on

      install: go get

      before_script:
        - wget https://github.com/go-task/task/releases/download/v2.4.0/task_linux_amd64.deb
        - sudo dpkg -i task_linux_amd64.deb
        - rm task_linux_amd64.deb
        - task install
      script:
        - task test

    - stage: deploy
      name: Deploy

      env:
        - GO111MODULE=on

      install: go get

      script:
        - wget https://github.com/go-task/task/releases/download/v2.4.0/task_linux_amd64.deb
        - sudo dpkg -i task_linux_amd64.deb
        - rm task_linux_amd64.deb
        - sudo curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o /usr/bin/semantic-release && sudo chmod +x /usr/bin/semantic-release
        - go get github.com/mitchellh/gox
        - go get github.com/tcnksm/ghr
        - export TRAVIS_JOB_NUMBER=WORKAROUND.1
      after_success:
        - semantic-release -ghr -vf
        - export VERSION=$(cat .version)
        - gox
            -ldflags "-s -w -X github.com/durandj/git-ignore/pkg/gitignore.VERSION="$VERSION
            -output "bin/{{ .Dir }}_v"$VERSION"_{{ .OS }}_{{ .Arch }}"
        - ghr $(cat .ghr) bin/

      if: branch = master AND type != pull_request
