language: go

go:
  - 1.11.x
  - master

env:
  - GO111MODULE=on

before_script:
  - go get -u -v github.com/go-task/task/cmd/task
  - task install

jobs:
  include:
    - stage: test
      script:
        - task test

    - stage: deploy
      script:
        - task deploy
      if: branch = master
