# https://taskfile.org

version: '2'

vars:
  BIN: git-ignore

tasks:
  default:
    cmds:
      - task: build

  build:
    vars:
      VERSION:
        sh: git describe --tags --always --dirty

    cmds:
      - go build
          -ldflags "-s -w -X github.com/durandj/git-ignore/pkg/gitignore.VERSION={{ .VERSION }}"
          -o {{ .BIN }}
          ./main.go

  clean:
    cmds:
      - rm --force --recursive {{ .BIN }} bin

  install:
    cmds:
      - go get github.com/onsi/ginkgo/ginkgo

  test:
    cmds:
      - ginkgo -v -p -race --randomizeAllSpecs ./pkg/gitignore
