# https://taskfile.org

version: '2'

vars:
  BIN: git-ignore

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - export VERSION=$(git describe --tags --always --dirty)
      - go build
          -ldflags "-s -w -X github.com/durandj/git-ignore/pkg/gitignore.VERSION={{ .VERSION }}"
          -o {{ .BIN }}
          ./main.go

  clean:
    cmds:
      - rm --force --recursive {{ .BIN }} bin

  install:
    cmds:
      - go get github.com/onsi/ginkgo/ginkgo

  release:
    cmds:
      - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o /usr/bin/semantic-release && chmod +x /usr/bin/semantic-release
      - go get github.com/mitchellh/gox
      - github.com/tcnksm/ghr
      - semantic-release -ghr -vf
      - export VERSION=$(cat .version)
      - gox
          -ldflags "-s -w -X github.com/durandj/git-ignore/pkg/gitignore.VERSION="$VERSION
          -output "bin/{{ .Dir }}_v"$VERSION"_{{ .OS }}_{{ .Arch }}"
      - ghr $(cat .ghr) bin/

  test:
    cmds:
      - ginkgo -v -p -race --randomizeAllSpecs ./pkg/gitignore
