# https://taskfile.org

version: '2'

vars:
  BIN: git-ignore
  # VERSION: { sh: git describe --tags --always --dirty }
  VERSION: 0.0.0

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go build
          -ldflags "-s -w -X github.com/durandj/git-ignore/pkg/gitignore.VERSION={{ .VERSION }}"
          -o {{ .BIN }}
          ./main.go

  clean:
    cmds:
      - rm --force {{ .BIN }}

  test:
    cmds:
      - ginkgo -v -p -race --randomizeAllSpecs ./pkg/gitignore
