name: CD

on:
  push:
    branches:
      - 'master'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: arduino/setup-task@v1
      - uses: actions/checkout@v3
      - name: Install Ginkgo
        run: go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
      - uses: actions/checkout@v3
      - name: Lint
        uses: golangci/golangci-lint-action@v3
      - name: Test
        run: task test
      - name: Build
        run: task build

  release:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
