---
name: CD

on:
  push:
    branches:
      - 'master'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - uses: arduino/setup-task@v2
      - uses: actions/checkout@v4
      - name: Lint
        uses: golangci/golangci-lint-action@v7
      - name: Test
        run: task test
      - name: Build
        run: task build
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: check

  release:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - uses: actions/checkout@v4
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: git fetch --force --tags
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
